version: 2.1
jobs:
  build:
    macos:
      xcode: "16.0.0"
    resource_class: m2pro.large
    steps:
      - checkout
      - run: "ls -ltR"
      - run: "xcodebuild -resolvePackageDependencies -project IceCubesApp.xcodeproj -scheme Env"
      - run: "xcodebuild build -scheme Env -project IceCubesApp.xcodeproj -destination generic/platform=iOS -IDEPostProgressNotifications=YES CODE_SIGN_IDENTITY=- AD_HOC_CODE_SIGNING_ALLOWED=YES COMPILER_INDEX_STORE_ENABLE=NO"