name: iOS starter workflow

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: macos-13

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Select Xcode
        run: |
          sudo xcode-select -switch /Applications/Xcode_16.app/Contents/Developer
      - name: Resolve Package Dependencies
        run: |
          xcodebuild -resolvePackageDependencies -project IceCubesApp.xcodeproj -scheme Env
      - name: Build
        run: |
          xcodebuild build -project IceCubesApp.xcodeproj -scheme Env -destination "generic/platform=iOS"
